version: '3'
services:
  front-end:
    image: "cloud-sync-frontend"
    working_dir: /home/node/app
    container_name: front-end
    build: ./cloud-sync-frontend
    volumes:
      - ./cloud-sync-frontend:/home/node/app
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - 3000:3000
    command: "npm start"

  server:
    image: "cloud-sync-backend"
    container_name: back-end
    build: ./cloud-sync-backend
    ports:
      - 5000:5000
    volumes:
      - ./cloud-sync-backend:/code
    environment:
      - FLASK_ENV=development
      - FLASK_APP=cloud-sync.py
      - FLASK_RUN_HOST=0.0.0.0
      - FRONTEND_URL=${FRONTEND_URL}
      - DATABASE_URL=${DATABASE_URL}
    command: "flask run"

  db:
    image: postgres:latest
    container_name: DB
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  
  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - 8080:8080
